// <auto-generated />
namespace Ovidos_Library.EntityLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LibraryDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LibraryDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201806072121395_LibraryDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
